# Generated by Django 5.1.6 on 2025-04-22 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_doctorprofile_location_alter_labreport_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='previsitreport',
            old_name='responses',
            new_name='conversation',
        ),
        migrations.RenameField(
            model_name='previsitreport',
            old_name='created_at',
            new_name='submitted_at',
        ),
        migrations.AlterField(
            model_name='doctorprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctors', to='api.department'),
        ),
        migrations.AlterField(
            model_name='previsitreport',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='previsit_report', to='api.appointment'),
        ),
    ]
